name: "AppImage"
description: "Builds a Linux AppImage on Debian 10 (Buster)"
inputs:
  executable:
    description: "Executable file"
    required: true
  icon-file:
    description: "Icon file to use for Executable"
    required: true
  desktop-file:
    description: "Desktop file to use for Executable"
    required: true


runs:
  using: composite

  steps:
    - name: Build packetry-x86_64.AppDir (Linux)
      shell: bash
      run: |
        DEPLOY_GTK_VERSION=4 linuxdeploy-x86_64.AppImage \
          --appimage-extract-and-run \
          --appdir packetry.AppDir \
          --executable=${{ inputs.executable }} \
          --icon-file ${{ inputs.icon-file }} \
          --plugin gtk \
          --desktop-file ${{ inputs.desktop-file }}

    - name: Shrink packetry-x86_64.AppDir (Linux)
      shell: bash
      run: |
        # cd to AppDir lib directory
        cd $GITHUB_WORKSPACE/packetry.AppDir/usr/lib

        # fix symlinks
        rm libgdk_pixbuf-2.0.so
        rm libgdk_pixbuf-2.0.so.0
        ln -s libgdk_pixbuf-2.0.so.0.4200.11 libgdk_pixbuf-2.0.so
        ln -s libgdk_pixbuf-2.0.so.0.4200.11 libgdk_pixbuf-2.0.so.0
        rm libgio-2.0.so
        rm libgio-2.0.so.0
        ln -s libgio-2.0.so.0.7600.0 libgio-2.0.so
        ln -s libgio-2.0.so.0.7600.0 libgio-2.0.so.0
        rm libgobject-2.0.so
        rm libgobject-2.0.so.0
        ln -s libgobject-2.0.so.0.7600.0 libgobject-2.0.so
        ln -s libgobject-2.0.so.0.7600.0 libgobject-2.0.so.0
        rm libpango-1.0.so
        rm libpango-1.0.so.0
        ln -s libpango-1.0.so.0.5400.0 libpango-1.0.so
        ln -s libpango-1.0.so.0.5400.0 libpango-1.0.so.0
        rm libpangocairo-1.0.so
        rm libpangocairo-1.0.so.0
        ln -s libpangocairo-1.0.so.0.5400.0 libpangocairo-1.0.so
        ln -s libpangocairo-1.0.so.0.5400.0 libpangocairo-1.0.so.0
        rm libpangoft2-1.0.so
        rm libpangoft2-1.0.so.0
        ln -s libpangoft2-1.0.so.0.5400.0 libpangoft2-1.0.so
        ln -s libpangoft2-1.0.so.0.5400.0 libpangoft2-1.0.so.0

        # remove some libraries we don't need
        rm libX*
        rm libblkid*
        rm libbsd*
        rm libcroco*
        rm libicu*
        rm libpixbufloader*
        rm libpixman*
        rm librsvg*
        rm libxcb-render*
        rm libxml*
        rm libzstd*

        # add some libraries we do need
        #
        # NB: $GTK4 is defined by the Dockerfile
        cp $GTK4/lib/x86_64-linux-gnu/libharfbuzz-gobject.so.0.40000.0 .
        ln -s libharfbuzz-gobject.so.0.40000.0 libharfbuzz-gobject.so.0
        ln -s libharfbuzz-gobject.so.0.40000.0 libharfbuzz-gobject.so
        cp $GTK4/lib/x86_64-linux-gnu/libharfbuzz-icu.so.0.40000.0 .
        ln -s libharfbuzz-icu.so.0.40000.0 libharfbuzz-icu.so.0
        ln -s libharfbuzz-icu.so.0.40000.0 libharfbuzz-icu.so
        cp $GTK4/lib/x86_64-linux-gnu/libharfbuzz.so.0.40000.0 .
        ln -s libharfbuzz.so.0.40000.0 libharfbuzz.so.0
        ln -s libharfbuzz.so.0.40000.0 libharfbuzz.so
        cp $GTK4/lib/x86_64-linux-gnu/libharfbuzz-subset.so.0.40000.0 .
        ln -s libharfbuzz-subset.so.0.40000.0 libharfbuzz-subset.so.0
        ln -s libharfbuzz-subset.so.0.40000.0 libharfbuzz-subset.so

        # strip all libraries
        strip lib*.so.*

        # return to workspace directory
        cd $GITHUB_WORKSPACE

    - name: Build packetry-x86_64.AppImage (Linux)
      shell: bash
      run: |
        appimagetool-x86_64.AppImage \
          --appimage-extract-and-run \
          packetry.AppDir/
